version: '3.8'
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST:-kafka}:${KAFKA_PORT:-9092}
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:${KAFKA_PORT:-9092}
    networks:
      - digirobotics-network

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - digirobotics-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    networks:
      - digirobotics-network

  elasticsearch:
    image: elasticsearch:8.12.1
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - digirobotics-network

networks:
  digirobotics-network:
    name: digirobotics-network